### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by adelcast** [aserg-ufmg/Truck-Factor#10]
Hi, I like the project, it shows pretty neat information!. I am not a Java expert, but I am changing the code to allow filtering by author (need to disregard the files that were calculated to have author X). I have the change ready, but I am having problems building the project since the pom.xml file doesn't define a Main-Class. Also, the name of the jar is gitdownloader-0.0.1z-SNAPSHOT.jar, which is a bit confusing since I was expecting the name to be gittruckfactor-0.0.1-SNAPSHOT.jar, or something among those lines.

To build, I am using "mvn package", am I missing something? Build instructions on README.md would be much appreciated.

**Comment by gavelino** [comment]
Hi,

I'm sorry for the delay in replying you. I'm also not a Java expert, especially in "build" matters. I'm not using **mvn** to compile my code. I use the Eclipse IDE to execute the code and the Export option to produce the runnable .jar file.  The pom.xml was automatically generated by the IDE.
Anyway, probably you can fix the problem by setting as Main-Class the class **aserg.gtf.truckfactor.TruckFactor.java**.

Let me know if this solves your problem. If this fixes the build problem, please, submit the changes in a pull request.
