### ISSUE TITLE
Warns that log4j is not initialized properly and reports no score

### ISSUE THREAD

**Issue by yeldiRium** [aserg-ufmg/Truck-Factor#14]
Hi,

for fun I tried to calculate the truck factor of [vscode](https://github.com/microsoft/vscode). I followed the [usage guide](https://github.com/aserg-ufmg/Truck-Factor#usage), skipping the optional linguist part.

I could package the jar just fine, but when running it I got this output:

```
> java -jar gittruckfactor-1.0.jar ../../../vscode microsoft/vscode
log4j:WARN No appenders could be found for logger (aserg.gtf.GitTruckFactor).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

Am I doing something wrong?

Kind regards
yeldiRium

**Comment by gavelino** [comment]
Hi, 

this is weird. The log4j messages are just warnings. They shouldn´t compromise the TF estimation. Did you execute the scripts before the .jar file? If so, could you please verify if any of the .log files produced are empty?

Best regards,

**Comment by yeldiRium** [comment]
Yes, I ran the scripts. The log files are inside the vscode project directory:

```
-rw-r--r--  1 --- --- 23536504  9. Okt 20:06 commitfileinfo.log
-rw-r--r--  1 --- --- 10389603  9. Okt 20:06 commitinfo.lo
```

Thank you for the quick response :)

If the log4j messages are just warnings and don't stop the program from working, the TF value should have been printed after them, right? I'm not sure what the expected output is.

**Comment by gavelino** [comment]
It also should be generated the file filelist.log. Is there this file? 

> If the log4j messages are just warnings and don't stop the program from working, the TF value should have been printed after them, right? I'm not sure what the expected output is.
Yes, if the process finishes it is printed the repository´s TF.

**Comment by yeldiRium** [comment]
Sorry for the delayed response. Yes, there is also a `filelist.log`, which is 225K big.

**Comment by gavelino** [comment]
Sorry for the delay. Could you provide all .log files. It will help me to investigate the problem.

**Comment by PepponeFX** [comment]
[commitfileinfo.log](https://github.com/aserg-ufmg/Truck-Factor/files/3989317/commitfileinfo.log)
[commitinfo.log](https://github.com/aserg-ufmg/Truck-Factor/files/3989318/commitinfo.log)
[filelist.log](https://github.com/aserg-ufmg/Truck-Factor/files/3989319/filelist.log)

Hi, here are the files generated by the commands as in the Readme example.

**Comment by gavelino** [comment]
Hi,

I think you forgot to set the repository's path of the project you want to estimate the TF. For example,  you should replace <git_repository_path>  for the project repository folder. 

./commit_log_script.sh <git_repository_path>

The logs you provided shown that you ran the scripts in the tool folder (path "git/Truck-Factor")

**Comment by PepponeFX** [comment]
[commitfileinfo.log](https://github.com/aserg-ufmg/Truck-Factor/files/3989521/commitfileinfo.log)
[commitinfo.log](https://github.com/aserg-ufmg/Truck-Factor/files/3989522/commitinfo.log)
[filelist.log](https://github.com/aserg-ufmg/Truck-Factor/files/3989523/filelist.log)

Sorry, this is the correct logs set (I hope). When I run the gittruckfactor tool (.jar) I don't get any result.

**Comment by gavelino** [comment]
I can´t reproduce your problem. Are you using the last compiled version of gittruckfactor.jar (release v1.2) or compiling your own version from the source code? 
Please, try to use the compiled version https://github.com/aserg-ufmg/Truck-Factor/releases/tag/v1.2. 

By using the v1.2 on your log files I got the following result:

" 2019-12-20 16:20:07 INFO  Extracting logCommits...  ../test/
2019-12-20 16:20:07 INFO  test: Extracting logCommitFiles...
2019-12-20 16:20:07 INFO  test: Extracting file information...
2019-12-20 16:20:07 WARN  LinguistExtractor:47 - linguistfiles.log not found. Executing without Linguist filter.
2019-12-20 16:20:07 INFO  test: Extracting and calculating authorship information...
2019-12-20 16:20:07 WARN  DOACalculator:92 - No commits for gittruckfactor/src/META-INF/MANIFEST.MF
TF = 1 (coverage = 2,50%)
TF authors (Developer;Files;Percentage):
Guilherme Avelino;78;97,50 "

**Comment by PepponeFX** [comment]
I tried both. Unfortunately with the same void result.

**Comment by gavelino** [comment]
No output at all? Any logger?

**Comment by PepponeFX** [comment]
I get only the log4j warns

**Comment by gavelino** [comment]
Please, show them here.

**Comment by PepponeFX** [comment]
Sorry for the late answer, I tried once again with the v1.2 and it does work.

**Comment by gavelino** [comment]
Great. Anyway, I’ll check the source code trying to identify the problem you mentioned.
