### ISSUE TITLE
No source available yet?

### ISSUE THREAD

**Issue by leni-kirilov** [aserg-ufmg/Truck-Factor#2]
I read the github pages and it contains lots of links to zips and tar files but no source files are yet available.
When will it be possible to try out the truck-factor tool for ourselves

**Comment by kernc** [comment]
:+1:

**Comment by mtov** [comment]
Hi, we are organizing and cleaning our code, so others can use it more easily. We promise to make it available in a couple of weeks.

**Comment by joaoarthurbm** [comment]
+1 request for the 'degree-of-authorship' calculator.

**Comment by chernjie** [comment]
@mtov looking forward to your source code!

**Comment by bzz** [comment]
Thank you for binging attention to this topic and looking forward to the source code!

**Comment by tpltnt** [comment]
:+1:

**Comment by DestyNova** [comment]
What is the truck factor of the truck factor repo?

**Comment by mtov** [comment]
Certainly, one (phd student). We are planning to make the source code available very soon, to see if this value increases!

**Comment by agh** [comment]
Excited to see this when the source surfaces!

**Comment by gavelino** [comment]
Source code is available
