### ISSUE TITLE
More to read

### ISSUE THREAD

**Issue by valeriocos** [aserg-ufmg/Truck-Factor#3]
Hi,
is there any chance to read more about your methodology, implementation and results to assess the truck factor?

cheers

**Comment by mtov** [comment]
Hi valerio, nice to hear from you. We started this idea after discussing with you about the bus/truck factor at SANER, in Montreal. We are finishing a paper about our study and promise to share with you the first drafts. Probably, we will have something readable in a couple of weeks.

**Comment by valeriocos** [comment]
Hi Marco,
this would be really nice from your side, I'm really interested in reading more about this topic.

cheers

**Comment by gavelino** [comment]
Link to a paper with more details is available in README
